[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "î€‡"
Alacritty = "ï„ "
Termite = "ï„ "
kitty = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Nautilus = "ðŸ“˜"
code-oss = "ï„¡"
VSCodium = "ï„¡"
Spotify = "ï†¼"
discord = "ïŽ’"
Eclipse= "ï“¤"
vlc="ï¡¼"
Google-chrome="ï‰¨"
Chromium="ï‰¨"
Slack="ï†˜"
notion-app="î¤…"
obsidian="î¤€"

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

[general]
separator = "|"
default_icon = "ï›¢"
wm_property = "class"

[options]
remove_duplicates = false
no_names = true
no_icon_names = false
